# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
#timeout_min: 60
#cpus_per_task: null
#gpus_per_node: null
tasks_per_node: 20
mem_gb: 128
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: noninterruptive
#qos: null
#comment: null
#constraint: null
exclude: ouga08,ouga09,ouga16
gres: gpu:a40:1
#cpus_per_gpu: null
#gpus_per_task: null
#mem_per_gpu: null
#mem_per_cpu: null
#account: null
#signal_delay_s: 120
#max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
#setup: null