_target_: src.models.motif_module.MotifLitModule
lr: 0.0003
weight_decay: 0.0005

net:
  _target_: src.models.networks.dss_resnet.DSSResNet
  d_input: 5
  d_output: 5
  d_model: 128
  n_layers: 4
  kernel_size: 15
  resnet_kernel_size: 7
  dropout: 0.2
  pe_when: Null
  pe: Null
