_target_: src.datamodules.motif_datamodule.MotifDataModule

# no recursion, because dataset will be instantiated several times in datamodule
_recursive_: False
dataset:
  _target_: src.datamodules.dna_datasets.CSVDataset

data:
  train_file: ${data_dir}ensembl_53_species_train.csv 
  test_file: ${data_dir}ensembl_53_test.csv 
  seq_position: "three_prime_region"

transforms: 
  _target_: src.datamodules.sequence_encoders.SequenceDataEncoder
  seq_len: 300
  total_len: 303 # length with padding
  mask_rate: 0.15
  split_mask: True

test_transforms: 
  _target_: src.datamodules.sequence_encoders.SequenceDataEncoderTest
  seq_len: 300
  total_len: 303 # length with padding
  mask_rate: 0.15
  split_mask: True

batched_dataset: False  # if batched dataset set batch size to 1
batch_size: 1024
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 16
pin_memory: False